modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="mobs_of_mobs"
version="R11"
displayName="Mobs of Mobs"
credits="Karogath helped us a lot"
displayURL="https://mcreator.net"
authors="crispy_chips1234,Aixiis, MCreator"
description='''
More Mobs and stuff
'''

[[dependencies.mobs_of_mobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



