modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/CrispyChips6660/mobs-of-mobs/issues"

[[mods]]
modId="mobs-of-mobs"
version="${file.jarVersion}"
displayName="Mobs Of Mobs"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="examplemod.png"
credits="Crispy, Blackout"
authors="Potatocult"
description='''A mod that adds more mobs'''

[[dependencies.mobs-of-mobs]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mobs-of-mobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
