modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="mobs_of_mobs"
version="R12"
displayName="Mobs of Mobs"
credits="My discord server"
displayURL="https://discord.gg/UNtBbx7"
authors="crispy_chips1234,Aixiis,Blackout"
description='''
More Mobs and stuff
'''

[[dependencies.mobs_of_mobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



