modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="mobs_of_mobs"
version="R10"
displayName="Mobs of Mobs"
credits="I don't want to credit anyone now go away"
displayURL="https://mcreator.net"
authors="crispy_chips1234, MCreator"
description='''
More Mobs
'''

[[dependencies.mobs_of_mobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



