modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/CrispyChips6660/mobs-of-mobs/issues"

[[mods]]
modId="mobsofmobs"
version="${file.jarVersion}"
displayName="Mobs Of Mobs"
updateJSONURL="https://raw.githubusercontent.com/potatomodders/Version/master/mobsofmobs_update.json"
displayURL="http://curseforge.com/minecraft/mc-mods/mobs-of-mobs/"
logoFile="mobs-of-mobs.png"
credits="Crispy, Blackout"
authors="Potatocult"
description='''A mod that adds more mobs'''

[[dependencies.mobsofmobs]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mobsofmobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
